import type { ThemeDefinition } from "../theme-types"

export const darkCyanTheme: ThemeDefinition = {
  id: "dark-cyan",
  name: "Dark Cyan",
  description: "Tema scuro elegante con accenti celesti",
  colors: {
    light: {
      bg: {
        dark: "#f8fafc",
        card: "#ffffff",
        darker: "#e2e8f0",
        hover: "#f1f5f9",
        input: "#ffffff",
        accordion: "#f8fafc",
        riepilogo: "#f1f5f9",
      },
      text: {
        primary: "#0f172a",
        secondary: "#475569",
        muted: "#64748b",
        icon: "#64748b",
        help: "#475569",
        accent: "#06b6d4",
        success: "#16a34a",
        error: "#dc2626",
      },
      border: {
        primary: "#e2e8f0",
        secondary: "#cbd5e1",
        accent: "#06b6d4",
        success: "#16a34a",
        error: "#dc2626",
      },
      button: {
        primary: "#06b6d4",
        primaryHover: "#0891b2",
        primaryText: "#ffffff",
        outlineBg: "transparent",
        outlineBorder: "#06b6d4",
        outlineText: "#06b6d4",
        outlineHover: "#06b6d4",
        success: "#16a34a",
        successHover: "#15803d",
        successText: "#ffffff",
        danger: "#dc2626",
        dangerHover: "#b91c1c",
        dangerText: "#ffffff",
      },
      table: {
        occupied: "#16a34a",
        occupiedText: "#ffffff"
      },
      step: {
        activeBg: "#06b6d4",
        activeText: "#ffffff",
        inactiveBg: "#f1f5f9",
        inactiveText: "#64748b",
        inactiveBorder: "#e2e8f0",
        completedText: "#16a34a",
        completedBorder: "#16a34a",
      },
      dialog: {
        bgOpacity: 0.95,
        backdropBlur: "12px",
        borderOpacity: 0.2,
      },
    },
    dark: {
      bg: {
        dark: "#0a0a0a",
        card: "#141414",
        darker: "#080808",
        hover: "#1f1f1f",
        input: "#1a1a1a",
        accordion: "#0f0f0f",
        riepilogo: "#1a1a1a",
      },
      text: {
        primary: "#e5e5e5",
        secondary: "#a3a3a3",
        muted: "#737373",
        icon: "#737373",
        help: "#a3a3a3",
        accent: "#06b6d4",
        success: "#22c55e",
        error: "#ef4444",
      },
      border: {
        primary: "#262626",
        secondary: "#404040",
        accent: "#06b6d4",
        success: "#22c55e",
        error: "#ef4444",
      },
      button: {
        primary: "#06b6d4",
        primaryHover: "#0891b2",
        primaryText: "#ffffff",
        outlineBg: "transparent",
        outlineBorder: "#06b6d4",
        outlineText: "#06b6d4",
        outlineHover: "#06b6d4",
        success: "#22c55e",
        successHover: "#16a34a",
        successText: "#ffffff",
        danger: "#ef4444",
        dangerHover: "#dc2626",
        dangerText: "#ffffff",
      },
      table: {
        occupied: "#047857",
        occupiedText: "#ffffff"
      },
      step: {
        activeBg: "#06b6d4",
        activeText: "#ffffff",
        inactiveBg: "#1a1a1a",
        inactiveText: "#737373",
        inactiveBorder: "#262626",
        completedText: "#22c55e",
        completedBorder: "#22c55e",
      },
      dialog: {
        bgOpacity: 0.98,
        backdropBlur: "16px",
        borderOpacity: 0.15,
      },
    },
  },
  defaults: {
    glassEffect: true,
  },
}